
version:  '3.8'
services:
  -notebooks:
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
          - ./data:/home/mambauser/data
          - ./notebooks:/home/mambauser/notebooks
        ports:
          - 8887:8888
        container_name: GIS-pydaybcn2022